import type { ImportSession, NormalizedImport } from "../core/ingestion-types";
import { importDateRange } from "../core/import-dates";

export interface ImportWorkspaceView {
  session: ImportSession;
  normalized: NormalizedImport;
  target: string;
  metadata: Record<string, string>;
  result?: { content: string; canExport: boolean; diagnostics: Array<{ severity: string; message: string }>; lossReport: string[] };
  canUndo: boolean;
  canRedo: boolean;
  structurePending?: boolean;
  presets: Array<{ id: string; name: string }>;
  page: number;
  notice: string;
}

const escape = (value: unknown): string => String(value ?? "").replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!);
const options = (values: Array<string | [string, string]>, current: string): string => values.map(value => {
  const [key, label] = typeof value === "string" ? [value, value] : value;
  return `<option value="${escape(key)}"${key === current ? " selected" : ""}>${escape(label)}</option>`;
}).join("");
const button = (action: string, label: string, extra = "", disabled = false): string => `<button type="button" class="btn" data-import-action="${action}" ${extra}${disabled ? " disabled" : ""}>${label}</button>`;
const fields: Array<[string, string]> = [
  ["", "Ignore / preserve source"], ["QSO_DATE", "QSO date"], ["TIME_ON", "Time (UTC)"], ["FREQ", "Frequency"], ["BAND", "Band"], ["MODE", "Mode"], ["SUBMODE", "Submode"], ["CALL", "Contacted callsign"], ["STATION_CALLSIGN", "Station callsign"], ["RST_SENT", "Sent report"], ["RST_RCVD", "Received report"], ["STX", "Sent serial"], ["SRX", "Received serial"], ["STX_STRING", "Sent exchange"], ["SRX_STRING", "Received exchange"], ["MY_GRIDSQUARE", "Station locator"], ["GRIDSQUARE", "Contacted locator"], ["QSO_POINTS", "QSO points"], ["COMMENT", "Comment"], ["OPERATOR", "Operator"],
  ["EDI_MODE_CODE", "EDI mode code"], ["EDI_NEW_EXCHANGE", "EDI new exchange (N)"], ["EDI_NEW_WWL", "EDI new locator (N)"], ["EDI_NEW_DXCC", "EDI new DXCC (N)"], ["EDI_DUPLICATE", "EDI duplicate (D)"],
];

export function renderImportWorkspace(state: ImportWorkspaceView): string {
  const { session, normalized } = state;
  const structureControls = `<fieldset class="import-structure-controls" data-import-structure-controls${state.structurePending ? " disabled" : ""}>`;
  const selected = session.candidates.find(candidate => candidate.id === session.selectedCandidateId);
  const included = session.rows.filter(row => row.included).length;
  const pages = Math.max(1, Math.ceil(session.rows.length / 30));
  const page = Math.min(Math.max(0, state.page), pages - 1);
  const pageRows = session.rows.slice(page * 30, (page + 1) * 30);
  const errors = normalized.issues.filter(issue => issue.severity === "error").length;
  const dates = importDateRange(normalized);
  const metadata: Record<string,string> = { ...normalized.metadata, contestStart: dates.start, contestEnd: dates.end, ...state.metadata };
  const metaInput = (key: string, label: string, placeholder = ""): string => {
    if (key === "exchange") { label = "Additional exchange (optional)"; placeholder = "Blank for RST, serial and locator only"; }
    return `<label class="field"><span>${escape(label)}</span><input class="input" data-import-field="metadata" data-import-value="${key}" value="${escape(metadata[key] ?? (key.startsWith("edi:") ? metadata[key.slice(4)] : ""))}" placeholder="${escape(placeholder)}">${key === "contestStart" || key === "contestEnd" ? '<small class="import-help">Defaults from the log; edit if official contest dates differ.</small>' : ""}</label>`;
  };
  const maxBoundary = Math.max(1, ...session.rows.slice(0, 100).map(row => Math.min(row.original.length, 4096)));
  return `<section class="import-workspace" aria-label="Advanced log import">
    <div class="import-heading"><div><p class="eyebrow">Import workbench · local processing</p><h2>Make every contact count.</h2><p>Review the structure, map your fields, then validate your export.</p></div><div class="import-actions">${button("legacy", "Classic table")}${button("undo", "Undo", "", !state.canUndo)}${button("redo", "Redo", "", !state.canRedo)}</div></div>
    <div class="import-summary" aria-label="Import summary"><div><strong>${normalized.records.length}</strong><span>contacts ready to review</span></div><div><strong>${session.columns.length}</strong><span>detected columns</span></div><div><strong>${session.rows.length - included}</strong><span>rows excluded</span></div><div class="${errors ? "import-attention" : ""}"><strong>${errors}</strong><span>issues requiring attention</span></div></div>
    ${state.notice ? `<p class="import-notice" role="status">${escape(state.notice)}</p>` : ""}
    ${session.warnings.length ? `<div class="import-notice">${session.warnings.map(warning => `<p>${escape(warning)}</p>`).join("")}</div>` : ""}

    ${structureControls}<details class="card import-stage" open><summary><span class="import-step">01</span><span>Structure <small>${escape(selected?.strategy ?? "Review parsing")} · ${Math.round(selected?.score ?? 0)}% confidence</small></span></summary><div class="import-stage-body">
      <div class="import-grid"><label class="field"><span>Parsing method</span><select class="select" data-import-field="strategy">${options([["auto", "Automatic detection"], ["delimited", "Delimited table"], ["whitespace", "Whitespace separated"], ["fixed-width", "Fixed-width columns"]], session.options.strategy ?? "auto")}</select></label>
      <label class="field"><span>Delimiter</span><select class="select" data-import-field="delimiter">${options([["\t", "Tab"], [",", "Comma"], [";", "Semicolon"], ["|", "Pipe"]], session.options.delimiter ?? selected?.delimiter ?? "\t")}</select></label>
      <label class="field"><span>Header source line (0 = none)</span><input class="input" type="number" min="0" data-import-field="headerRow" value="${session.options.headerRow === undefined ? "" : session.options.headerRow === null ? "0" : session.options.headerRow + 1}" placeholder="Blank = automatic"></label><div class="import-actions">${button("reparse", "Detect again")}</div></div>
      <details class="import-disclosure"><summary>Compare parsing interpretations</summary><div class="import-candidates">${session.candidates.map(candidate => `<label class="import-candidate ${candidate.id === session.selectedCandidateId ? "selected" : ""}"><input type="radio" name="import-candidate" data-import-field="candidate" value="${escape(candidate.id)}"${candidate.id === session.selectedCandidateId ? " checked" : ""}><span><strong>${escape(candidate.strategy)} · ${candidate.width} columns · ${Math.round(candidate.score)}%</strong><small>${candidate.id === session.selectedCandidateId ? "Selected interpretation. " : "Alternative. "}${escape(candidate.reasons.join(" · "))}</small></span></label>`).join("")}</div></details>
      <details class="import-disclosure"${session.options.strategy === "fixed-width" ? " open" : ""}><summary>Adjust fixed-width boundaries</summary><p class="import-help">Drag a boundary or enter its character position. The original text remains available below.</p><div class="import-boundaries">${(session.options.boundaries ?? selected?.boundaries ?? []).map((boundary, index) => `<div class="import-boundary"><label for="import-boundary-${index}">Boundary ${index + 1}</label><input id="import-boundary-${index}" type="range" min="1" max="${maxBoundary}" value="${boundary}" data-import-field="boundary" data-import-index="${index}"><input class="input" aria-label="Boundary ${index + 1} character position" type="number" min="1" max="${maxBoundary}" value="${boundary}" data-import-field="boundary" data-import-index="${index}">${button("boundary-delete", "Remove", `data-import-index="${index}"`)}</div>`).join("")}</div><div class="import-actions"><label class="field"><span>New boundary position</span><input class="input" id="import-boundary-new" type="number" min="1" max="${maxBoundary}" value="10"></label>${button("boundary-add", "Add boundary")}</div></details>
      <details class="import-disclosure"><summary>Original source · preserved unchanged</summary><pre class="code-preview">${escape(session.source.slice(0, 60000))}</pre>${session.source.length > 60000 ? '<p class="import-help">Preview limited to 60,000 characters. The full original is preserved in the conversion report.</p>' : ""}</details>
    </div></details></fieldset>

    ${structureControls}<details class="card import-stage" open><summary><span class="import-step">02</span><span>Field mapping <small>Confirm sent and received columns before exporting</small></span></summary><div class="import-stage-body"><div class="import-mappings">${session.columns.map((column, index) => {
      const samples = session.rows.filter(row => row.included && row.cells[index]).slice(0, 3).map(row => row.cells[index]);
      return `<article class="import-mapping"><div class="import-column-heading"><span class="import-column-number">${index + 1}</span><strong>${escape(column.name || `Column ${index + 1}`)}${column.locked ? " · manual" : ""}</strong><span class="import-confidence ${column.confidence < .75 ? "uncertain" : ""}">${Math.round(column.confidence * 100)}%</span></div><p class="import-samples" title="${escape(samples.join(" · "))}">${escape(samples.join(" · ") || "No sample values")}</p><label class="field"><span>Field meaning</span><select class="select" data-import-field="mapping" data-import-index="${index}">${options(fields.some(([key]) => key === column.field) ? fields : [...fields, [column.field, column.field]], column.field)}</select></label><details class="import-disclosure"><summary>Evidence & transformations</summary><p class="import-help">${escape(column.reasons.join(" · ") || "No confident mapping evidence. Please choose a field.")}</p><div class="import-stack"><label class="field"><span>Date order</span><select class="select" data-import-field="dateOrder" data-import-index="${index}">${options([["auto", "Automatic"], ["ymd", "Year / month / day"], ["dmy", "Day / month / year"], ["mdy", "Month / day / year"]], column.transform.dateOrder ?? "auto")}</select></label><label class="field"><span>Frequency unit</span><select class="select" data-import-field="frequencyUnit" data-import-index="${index}">${options(["auto", "MHz", "kHz", "Hz"], column.transform.frequencyUnit ?? "auto")}</select></label><label class="field"><span>Constant value (optional)</span><input class="input" data-import-field="constant" data-import-index="${index}" value="${escape(column.transform.constant)}" placeholder="Use this value for every row"></label><label class="import-check"><input type="checkbox" data-import-field="uppercase" data-import-index="${index}"${column.transform.uppercase ? " checked" : ""}> Normalize to uppercase</label><label class="field"><span>Split separator</span><input class="input" id="import-split-${index}" value=" " placeholder="Space for whitespace, or a literal delimiter"></label>${button("split", "Split column", `data-import-index="${index}"`)}<label class="field"><span>Join columns (1-based)</span><input class="input" id="import-join-${index}" placeholder="e.g. 7, 8" value="${index + 1}"></label>${button("join", "Combine columns", `data-import-index="${index}"`)}</div></details></article>`;
    }).join("")}</div><div class="import-actions">${button("add-column", "Add a constant column")}</div>
    <details class="import-disclosure"><summary>Reuse a mapping preset</summary><div class="import-actions"><label class="field"><span>Preset name</span><input class="input" id="import-preset-name" placeholder="My logger export"></label>${button("preset-save", "Save current mapping")}</div><div class="import-stack">${state.presets.map(preset => `<div class="import-preset"><strong>${escape(preset.name)}</strong><div class="import-actions">${button("preset-apply", "Apply", `data-import-value="${escape(preset.id)}"`)}${button("preset-delete", "Delete", `data-import-value="${escape(preset.id)}"`)}</div></div>`).join("") || '<p class="import-help">Your saved presets stay in this browser.</p>'}</div></details></div></details></fieldset>

    <details class="card import-stage"><summary><span class="import-step">03</span><span>Rows & provenance <small>Include, classify, edit, and compare ${session.rows.length} source rows</small></span></summary><div class="import-stage-body"><p class="import-help">Edits update the working copy. Expand a row to compare the original and normalized fields.</p>${structureControls}<div class="import-row-list">${pageRows.map(row => {
      const record = normalized.records.find(item => item.id === row.id || item.sourceIndex === row.sourceIndex);
      return `<details class="import-row"><summary><span class="import-row-line">Line ${row.sourceIndex + 1}</span><span class="import-row-sample">${escape(row.cells.join(" · ") || row.kind)}</span><span class="import-tag">${row.included ? "Included" : row.kind}</span>${row.warnings.length || record?.issues.length ? '<span class="import-attention">Review</span>' : ""}</summary><div class="import-row-body"><div class="import-actions"><label class="import-check"><input type="checkbox" data-import-field="row-included" data-import-index="${row.sourceIndex}"${row.included ? " checked" : ""}> Include in export</label><label class="field"><span>Row classification</span><select class="select" data-import-field="row-kind" data-import-index="${row.sourceIndex}">${options(["qso", "header", "comment", "blank", "metadata", "summary"], row.kind)}</select></label></div><pre class="code-preview">${escape(row.original)}</pre><div class="import-grid">${session.columns.map((column, index) => `<label class="field"><span>${escape(column.name)} · ${escape(column.field || "Unmapped")}</span><input class="input" aria-label="Line ${row.sourceIndex + 1}, column ${index + 1}" data-import-field="cell" data-import-index="${row.sourceIndex}" data-import-value="${index}" value="${escape(row.cells[index])}"></label>`).join("")}</div>${row.warnings.map(warning => `<p class="import-attention">${escape(warning)}</p>`).join("")}${record ? `<div class="import-scroll" tabindex="0" role="region" aria-label="Normalized values for line ${row.sourceIndex + 1}"><table class="import-provenance"><thead><tr><th>Field</th><th>Original</th><th>Normalized</th><th>Why it changed</th></tr></thead><tbody>${Object.entries(record.values).map(([field, value]) => `<tr><th scope="row">${escape(field)}</th><td>${escape(record.provenance[field]?.map(item => item.original).join(" + "))}</td><td>${escape(value)}</td><td>${escape(record.provenance[field]?.flatMap(item => item.transformations).join(" · ") || "Preserved")}</td></tr>`).join("")}</tbody></table></div>${Object.keys(record.unmapped).length ? `<p class="import-help">Preserved unmapped values: ${escape(JSON.stringify(record.unmapped))}</p>` : ""}${record.issues.map(issue => `<p class="import-attention">${escape(issue.message)}</p>`).join("")}` : ""}</div></details>`;
    }).join("")}</div></fieldset><div class="import-pagination">${button("page-prev", "Previous 30", "", page === 0)}<span>Page ${page + 1} of ${pages}</span>${button("page-next", "Next 30", "", page + 1 >= pages)}</div></div></details>

    <details class="card import-stage" open><summary><span class="import-step">04</span><span>Export settings <small>Complete contest metadata and check the result</small></span></summary><div class="import-stage-body"><div class="import-grid"><label class="field"><span>Output format</span><select class="select" data-import-field="target">${options([["adif", "ADIF (.adi)"], ["adx", "ADX XML (.adx)"], ["cabrillo", "Cabrillo (.log)"], ["edi", "REG1TEST EDI (.edi)"], ["csv", "CSV (.csv)"]], state.target)}</select></label>${metaInput("stationCall", "Station callsign", "S53ZO")}${metaInput("stationLocator", "Station locator", "JN86CR")}${metaInput("band", "Band", "144 MHz")}</div><div class="import-actions">${button("promote", "Use consistent station values")}</div>
      <div class="import-grid">${metaInput("contestName", "Contest name / identifier")}${metaInput("contestStart", "Contest start date", "YYYYMMDD")}${metaInput("contestEnd", "Contest end date", "YYYYMMDD")}${metaInput("section", "Entry section / category")}</div><label class="import-check"><input type="checkbox" data-import-field="metadata" data-import-value="utcConfirmed"${metadata.utcConfirmed === "true" ? " checked" : ""}> I confirm the logged times are UTC</label><label class="field"><span>Scoring rules</span><select class="select" data-import-field="metadata" data-import-value="scoring">${options([["", "Choose scoring rules"], ["supplied-points", "Preserve supplied QSO points; no multipliers"], ["claimed", "Use an explicit contest claimed score"]], metadata.scoring ?? "")}</select></label>${metaInput("claimedScore", "Claimed total score", "Required for explicit claimed scoring")}<details class="import-disclosure"><summary>Operator, equipment & additional metadata</summary><div class="import-grid">${[["operator", "Operator"], ["club", "Club"], ["exchange", "Exchange definition"], ["power", "Transmit power (W)"], ["transmitter", "Transmitter"], ["receiver", "Receiver"], ["antenna", "Antenna"], ["antennaHeight", "Antenna height"], ["name", "Operator name"], ["address", "Address"], ["email", "Email"]].map(([key, label]) => metaInput(key!, label!)).join("")}</div></details>
      ${state.target === "edi" ? `<details class="import-disclosure"><summary>EDI multiplier and bonus declarations</summary><p class="import-help">Supply the contest's declarations when needed. Count fields use count;bonus;multiplier. Blank fields remain unspecified. These values never replace recorded QSO points.</p><div class="import-grid">${[["CWWLs", "Locator count;bonus;multiplier"], ["CWWLB", "Locator bonus points"], ["CExcs", "Exchange count;bonus;multiplier"], ["CExcB", "Exchange bonus points"], ["CDXCs", "DXCC count;bonus;multiplier"], ["CDXCB", "DXCC bonus points"]].map(([key,label]) => metaInput(`edi:${key}`, label!)).join("")}</div></details>` : ""}
      ${normalized.issues.length ? `<details class="import-disclosure"><summary>${normalized.issues.length} import diagnostics</summary><ul class="import-diagnostics">${normalized.issues.slice(0, 100).map(issue => `<li><strong>${escape(issue.severity)}</strong> ${escape(issue.message)}${issue.field ? ` <code>${escape(issue.field)}</code>` : ""}</li>`).join("")}</ul>${normalized.issues.length > 100 ? '<p class="import-help">Showing the first 100 diagnostics. Download the report for all details.</p>' : ""}</details>` : ""}
      <div class="import-export-bar"><div><strong>${state.result?.canExport ? "Validated and ready" : "Validate before downloading"}</strong><p>${state.result?.canExport ? "Review the preview and format warnings below." : "Automatic recovery can try better interpretations. Review any unresolved choices."}</p><p>The conversion report retains original source and transformation details.</p></div><div class="import-actions">${button("recover", "Try automatic recovery")}${button("preview", "Validate & preview")}${button("download", "Download log", "", !state.result?.canExport)}${button("report", "Conversion report")}</div></div>
      ${state.result ? `<div class="import-result" aria-live="polite">${state.result.diagnostics.length ? `<ul class="import-diagnostics">${state.result.diagnostics.slice(0, 100).map(item => `<li><strong>${escape(item.severity)}</strong> ${escape(item.message)}</li>`).join("")}</ul>` : '<p class="import-success">No export validation errors.</p>'}${state.result.lossReport.length ? `<details class="import-disclosure" open><summary>Destination limitations · ${state.result.lossReport.length}</summary><ul>${state.result.lossReport.slice(0, 100).map(item => `<li>${escape(item)}</li>`).join("")}</ul>${state.result.lossReport.length > 100 ? '<p class="import-help">Showing the first 100 destination limitations. The conversion report contains all details.</p>' : ""}<p class="import-help">Keep the conversion report alongside the exported log to retain source details.</p></details>` : ""}<pre class="code-preview" tabindex="0" aria-label="Export preview">${escape(state.result.content.slice(0, 60000))}</pre>${state.result.content.length > 60000 ? '<p class="import-help">Preview limited to 60,000 characters. Download contains the complete output.</p>' : ""}</div>` : ""}
    </div></details>
  </section>`;
}
